import React from 'react';

function Timeline(props) {
    return (
        <div>
            <p>In the beginning of the first semester of sophomore year, the plan is to consult the librarian and gather literature for review and discussion with the team. Also, the division of literature between each of the members to review and summarize will begin. The next step would be to create a list of experts and consultants and set up meetings with them to get more information on the topic and find out possible research paths. This will hopefully lead us to having a clear idea and plan for the research project. Once a clear focus is established, the team will start exploring possible methodologies for data collection and analysis. By the end of the first semester of sophomore year, the initial draft of the team’s research proposal should be completed. Additionally, we would have divided roles and responsibilities for the duration of the research process so that progress can be maximized.</p>
            <p>At the beginning of the second semester of sophomore year, our thesis proposal should be complete and will be presented to the committee. During this time, the team should also have a clear understanding of how data will be collected and a list of research sites or individuals required for the study to be conducted. If required, the IRB or IACUC should be completed no later than the August before junior year. We will continue to review literature for the final thesis and also have a list of scholarly meetings, conferences, and journals that could be a possible forum for the research. During this semester, we should have an idea of possible funding sources for the team’s research and start applying for appropriate grants. By the end of the semester, the team budget should be set and the first draft of the team website should be ready.</p>
            <p>Early in the first semester of junior year, IRB or IACUC approval should be received if it is required for research. During this semester, data collection will begin along with any kind of research activities such as surveys, interviews or focus groups, working in the lab, or finishing the first draft of a prototype. The team website should be updated as needed throughout this semester and during the future semesters. The team should also be continuing to review literature, finding possible forums for research, and finding possible funding sources consistently from now until the second semester of senior year. At the Fall Colloquia, the team will present research and progress. Finally, the outline of the final thesis should be developed by the end of the semester.</p>
            <p>During the second semester of junior year, the team will finish data collection and complete most of data analysis by the end of the school year. After that we should have an initial draft of the first three chapters of the final thesis and get feedback on the draft from our mentor, librarian, and expert contacts or discussants. In April, the team will present a poster at the Undergraduate Research Day. Additionally, we should consider making a proposal for a meeting or conference.</p>
            <p>Within the first month of the first semester of senior year, the data collection and analysis should be completed. Next, we should have a complete draft of the final thesis finished and start revising the draft after consulting with our mentor, librarian, and expert contacts or discussants. Afterwards, we will start working on a draft of the team’s presentation for the team thesis conference rehearsal. By the end of this semester, we should have a list of at least five names of experts who have been invited and have agreed to be reviewers or discussants at the thesis conference.</p>
            <p>In early February during the second semester of senior year, the team will do the thesis conference rehearsal and submit final team information as required by Gemstone. The team thesis should be completed and a draft should be ready to submit. During the team thesis conference, all members will be presenting and defending the team thesis. Subsequently, the final thesis will be submitted and our team mentor will officially sign off on the final thesis.</p>
        </div>
    );
}

export default Timeline;